# Generated by Django 4.2.7 on 2024-08-03 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminfront', '0006_cart_created_at_cart_utilisateur_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_livraison', models.DateTimeField(default=django.utils.timezone.now)),
                ('adresse_livraison', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('LIVREE', 'Livrée')], default='EN_ATTENTE', max_length=50)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='adminfront.commande')),
            ],
        ),
    ]
