# Generated by Django 4.2.7 on 2024-08-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminfront', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='numero_de_telephone',
            field=models.IntegerField(default=22890912367),
        ),
    ]
