# Generated by Django 4.2.30 on 2026-08-24 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("adminfront", "0009_administrateur_numero_de_telephone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="administrateur",
            options={
                "ordering": ["-id"],
                "verbose_name": "Utilisateur / Administrateur",
                "verbose_name_plural": "Utilisateurs / Administrateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="categorie",
            options={
                "ordering": ["nom"],
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
            },
        ),
        migrations.AlterModelOptions(
            name="commande",
            options={
                "ordering": ["-date_commande", "-id"],
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
            },
        ),
        migrations.AlterModelOptions(
            name="livraison",
            options={
                "ordering": ["-id"],
                "verbose_name": "Livraison",
                "verbose_name_plural": "Livraisons",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-date_creation", "-id"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="produit",
            options={
                "ordering": ["-date_ajout", "-id"],
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
            },
        ),
        migrations.AddField(
            model_name="administrateur",
            name="date_inscription",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date d'inscription"
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="date_ajout",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date d'ajout"
            ),
        ),
        migrations.AlterField(
            model_name="administrateur",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="administrateur",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="administrateur",
            name="is_staff",
            field=models.BooleanField(
                default=False, verbose_name="Équipe administrative"
            ),
        ),
        migrations.AlterField(
            model_name="administrateur",
            name="nom",
            field=models.CharField(max_length=50, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="administrateur",
            name="nomutilisateur",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Nom d'utilisateur"
            ),
        ),
        migrations.AlterField(
            model_name="administrateur",
            name="numero_de_telephone",
            field=models.CharField(
                blank=True,
                default="+22890912367",
                max_length=30,
                verbose_name="Numéro de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="administrateur",
            name="photo_de_profil",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos_profil/",
                verbose_name="Photo de profil",
            ),
        ),
        migrations.AlterField(
            model_name="administrateur",
            name="prenom",
            field=models.CharField(max_length=50, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="categorie",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="categorie",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/",
                verbose_name="Image de catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="categorie",
            name="nom",
            field=models.CharField(max_length=100, verbose_name="Nom de la catégorie"),
        ),
        migrations.AlterField(
            model_name="commande",
            name="adresse_livraison",
            field=models.CharField(max_length=255, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="commande",
            name="code_postal",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Code postal"
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="date_commande",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de commande"
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="etat_commande",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente"),
                    ("EN_TRAITEMENT", "En traitement"),
                    ("EXPEDIE", "Expédié"),
                    ("LIVRE", "Livré"),
                    ("ANNULE", "Annulé"),
                ],
                default="EN_ATTENTE",
                max_length=50,
                verbose_name="État de la commande",
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="pays",
            field=models.CharField(default="Togo", max_length=100, verbose_name="Pays"),
        ),
        migrations.AlterField(
            model_name="commande",
            name="total",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Total (FCFA)"
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="ville",
            field=models.CharField(max_length=100, verbose_name="Ville"),
        ),
        migrations.AlterField(
            model_name="elementcommande",
            name="prix_unitaire",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="elementcommande",
            name="quantite",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="livraison",
            name="adresse_livraison",
            field=models.CharField(max_length=255, verbose_name="Adresse de livraison"),
        ),
        migrations.AlterField(
            model_name="livraison",
            name="code_postal",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Code postal"
            ),
        ),
        migrations.AlterField(
            model_name="livraison",
            name="date_livraison",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Date de livraison prévue",
            ),
        ),
        migrations.AlterField(
            model_name="livraison",
            name="pays",
            field=models.CharField(default="Togo", max_length=100, verbose_name="Pays"),
        ),
        migrations.AlterField(
            model_name="livraison",
            name="statut",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente"),
                    ("EN_COURS", "En cours de livraison"),
                    ("LIVREE", "Livrée"),
                    ("ANNULEE", "Annulée"),
                ],
                default="EN_ATTENTE",
                max_length=50,
                verbose_name="Statut livraison",
            ),
        ),
        migrations.AlterField(
            model_name="livraison",
            name="ville",
            field=models.CharField(max_length=100, verbose_name="Ville"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="date_creation",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="lu",
            field=models.BooleanField(default=False, verbose_name="Lu"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="produit",
            name="categorie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="adminfront.categorie",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="description",
            field=models.TextField(verbose_name="Description détaillée"),
        ),
        migrations.AlterField(
            model_name="produit",
            name="image",
            field=models.ImageField(
                upload_to="produits/", verbose_name="Image du produit"
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="nom",
            field=models.CharField(max_length=150, verbose_name="Nom du produit"),
        ),
        migrations.AlterField(
            model_name="produit",
            name="prix",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Prix (FCFA)"
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="quantite",
            field=models.IntegerField(default=0, verbose_name="Quantité en stock"),
        ),
    ]
