# Generated by Django 4.2.30 on 2026-08-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "adminfront",
            "0010_alter_administrateur_options_alter_categorie_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="administrateur",
            name="email_verifie",
            field=models.BooleanField(default=True, verbose_name="Email vérifié"),
        ),
    ]
